apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure
  - namespace.yaml
  # Sliver C2 server (single static instance)
  - sliver/pvc.yaml
  - sliver/deployment.yaml
  - sliver/service.yaml
  # Network policies
  - netpol/00-default-deny.yaml
  - netpol/01-allow-kube-dns.yaml
  - netpol/03-sliver.yaml
